# .gitlab-ci.yml
pages:
  stage: deploy
  image: python:3.9 # Use a Python Docker image
  script:
    - pip install -U sphinx sphinx-rtd-theme # Install Sphinx and dependencies
    - sphinx-build -b html docs/source public # Build docs into the 'public' folder
  artifacts:
    paths:
      - public # Tell 
