[project]
name = "oci-policy-analysis"
description = "OCI Policy Analysis"
readme = "README.md"
authors = [{ name = "Andrew Gregory" }]
requires-python = ">=3.12"
license = { text = "UPL-1.0" }
dynamic = []
version = "0.0.0"

dependencies = [
    "oci>=2.144.1",
    "deepdiff>=8.5.0",
    "fastmcp>=2.12.3",
]

classifiers = [
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: Universal Permissive License (UPL)",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Tools",
]

[build-system]
requires = ["setuptools>=61.0", "wheel", "setuptools_scm>=8"]
build-backend = "setuptools.build_meta"

