[project]
name = "oci-policy-analysis"
description = "OCI Policy Analysis"
readme = "README.md"
authors = [{ name = "Andrew Gregory" }]
requires-python = ">=3.12"
license = { text = "UPL-1.0" }
dynamic = []
version = "5.2.0"

dependencies = [
    "oci==2.168.0",
    "deepdiff==8.5.0",
    "antlr4-python3-runtime==4.13.2"
]

classifiers = [
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: Universal Permissive License (UPL)",
    "Intended Audience :: Developers",
    "Topic :: Software Development",
]

[project.optional-dependencies]
core = []
ui = []
web = [
    "fastapi>=0.110",
    "uvicorn>=0.29",
    "itsdangerous>=2.2"
]
mcp = [
    "fastmcp==2.12.5"
]
all = [
    "fastapi>=0.110",
    "uvicorn>=0.29",
    "itsdangerous>=2.2",
    "fastmcp==2.12.5"
]
docs = [
    "sphinx>=7",
    "sphinx-rtd-theme>=3",
    "myst-parser>=2",
    "sphinxcontrib-mermaid>=2"
]
commit = [
    "pipdeptree>=2.30.0",
    "pre_commit>=4.5.0",
]
test = [
    "pytest"
]

[project.scripts]
oci-policy-analysis-ui = "oci_policy_analysis.main:main"
oci-policy-analysis-cli = "oci_policy_analysis.cli:main"
oci-policy-analysis-web = "oci_policy_analysis.web.main:main"
oci-policy-analysis-mcp = "oci_policy_analysis.mcp_server:main"

[build-system]
requires = ["setuptools>=61.0", "wheel", "setuptools_scm>=8"]
build-backend = "setuptools.build_meta"

[tool.setuptools.package-data]
"oci_policy_analysis.web" = ["static/*", "static/**/*"]
