[project]
name = "oci-policy-analysis"
description = "OCI Policy Analysis"
readme = "README.md"
authors = [{ name = "Andrew Gregory" }]
requires-python = ">=3.12"
license = { text = "UPL-1.0" }
dynamic = []
version = "4.6.0"

dependencies = [
    "oci==2.168.0",
    "deepdiff==8.5.0",
    "fastmcp==2.12.5",
    "antlr4-python3-runtime==4.13.2"
]

classifiers = [
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: Universal Permissive License (UPL)",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Tools",
]

[project.optional-dependencies]
docs = [
    "sphinx>=7",
    "sphinx-rtd-theme>=3",
    "myst-parser>=2",
    "sphinxcontrib-mermaid>=2"
]
commit = [
    "pipdeptree>=2.30.0",
    "pre_commit>=4.5.0",
]
test = [
    "pytest"
]

[build-system]
requires = ["setuptools>=61.0", "wheel", "setuptools_scm>=8"]
build-backend = "setuptools.build_meta"
