# ruff.toml — standalone linter configuration
line-length = 120
target-version = "py312"

[lint]
select = [
    "E", "W", "F", "I", "B", "C", "UP",
]
ignore = ["E501"]

[format]
quote-style = "single"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

exclude = [
    ".git",
    "__pycache__",
    "build",
    "dist",
    "src/sample",
    "src/oci_policy_analysis/logic/parsers/policy_parser",
    "src/oci_policy_analysis/logic/parsers/condition_parser",
    "src/oci_policy_analysis/logic/parsers/policy_parser/*",
    "src/oci_policy_analysis/logic/parsers/condition_parser/*",
]
